name: todo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  country_picker: ^2.0.27
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.7
  faker: ^2.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_cache_manager: ^3.4.1
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.2
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.16
  get_it: ^8.0.3
  go_router: ^14.6.2
  image_cropper: ^8.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.3.0
  mobile_scanner: ^6.0.2
  permission_handler: ^11.3.1
  pretty_qr_code: ^3.3.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/core/common/assets/images/
    - lib/core/common/assets/icons/
    - lib/core/common/assets/animations/
    - .env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: DMSans
      fonts:
        - asset: lib/core/common/assets/fonts/english/DMSans-Black.ttf
          weight: 900
        - asset: lib/core/common/assets/fonts/english/DMSans-ExtraBold.ttf
          weight: 800
        - asset: lib/core/common/assets/fonts/english/DMSans-Bold.ttf
          weight: 700
        - asset: lib/core/common/assets/fonts/english/DMSans-SemiBold.ttf
          weight: 600
        - asset: lib/core/common/assets/fonts/english/DMSans-Medium.ttf
          weight: 500
        - asset: lib/core/common/assets/fonts/english/DMSans-Regular.ttf
          weight: 400
        - asset: lib/core/common/assets/fonts/english/DMSans-Light.ttf
          weight: 300
        - asset: lib/core/common/assets/fonts/english/DMSans-ExtraLight.ttf
          weight: 200
        - asset: lib/core/common/assets/fonts/english/DMSans-Thin.ttf
          weight: 100
    - family: Almarai
      fonts:
        - asset: lib/core/common/assets/fonts/arabic/Almarai-Bold.ttf
          weight: 700
        - asset: lib/core/common/assets/fonts/arabic/Almarai-ExtraBold.ttf
          weight: 800
        - asset: lib/core/common/assets/fonts/arabic/Almarai-Light.ttf
          weight: 300
        - asset: lib/core/common/assets/fonts/arabic/Almarai-Regular.ttf
          weight: 400
        - asset: lib/core/common/assets/fonts/arabic/Almarai-Regular.ttf
          weight: 500
        - asset: lib/core/common/assets/fonts/arabic/Almarai-Bold.ttf
          weight: 600
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/english/TrajanPro.ttf
  #       - asset: fonts/english/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_intl:
  enabled: true

# flutter_assets:
#   assets_path: lib/core/common/assets/images
#   output_path: lib/core/theme
#   filename: app_images.dart
#   ignore_comments: true
#   field_prefix: null
#   classname: AppImages
flutter_assets:
  assets_path: lib/core/common/assets/icons
  output_path: lib/core/theme
  filename: app_icons.dart
  ignore_comments: true
  field_prefix: null
  classname: AppIcons
flutter_launcher_icons:
  android: "todo_launcher"
  ios: true
  image_path: "lib/core/common/assets/images/app_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_foreground: "lib/core/common/assets/images/app_launcher.png"
  adaptive_icon_background: "#5F33E1"

# flutter_assets:
#   assets_path: lib/core/common/assets/animations
#   output_path: lib/core/theme
#   filename: app_animations.dart
#   ignore_comments: true
#   field_prefix: null
#   classname: AppAnimations
